{
 "title": "Endpoint Status",
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(probe_success, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{instance=\"$instance\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "HTTP Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "TLS",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_ssl{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime (1d)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$instance\"}[1d])"
    }
   ]
  },
  {
   "title": "Uptime (7d)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(probe_success{instance=~\"$instance\"}[7d])"
    }
   ]
  },
  {
   "title": "History",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Apdex",
   "type": "bargauge",
   "description": "Latest value may be slightly lower than actual",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(\r\n    (count_over_time(job:probe_duration_seconds:satisfied{instance=\"$instance\"}[$__interval]) or on() 0 * count_over_time(probe_duration_seconds{instance=\"$instance\"}[$__interval]))\r\n    + ((count_over_time(job:probe_duration_seconds:tolerating{instance=\"$instance\"}[$__interval]) or on() 0 * count_over_time(probe_duration_seconds{instance=\"$instance\"}[$__interval])) / 2)\r\n) / count_over_time(probe_duration_seconds{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Apdex"
    },
    { "expr": "hour()", "legendFormat": "UTC Hour" }
   ]
  }
 ]
}