{
 "title": "Kubernetes Pods Resources Allocation & Usage",
 "description": "Overview of pod & node resource requests, limits and usages",
 "tags": [
  "resources",
  "cluster"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_info, node)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node!=\"\", node=~\"$node\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node!=\"\", node=~\"$node\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=~\"$node\", name!=\"\"}[5m]))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 3 }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\"})",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node!=\"\", node=~\"$node\"})",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", node!=\"\", node=~\"$node\"})",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$node\", name!=\"\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Node Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"$node\"}) by (node)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", node!=\"\", node=~\"$node\"}) by (node)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", node!=\"\", node=~\"$node\"}) by (node)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{node=~\"$node\", name!=\"\"}[5m])) by (node)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\", node=~\"$node\"}) by (node)",
     "legendFormat": "Allocatable"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", node!=\"\", node=~\"$node\"}) by (node)",
     "legendFormat": "Requested"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", node!=\"\", node=~\"$node\"}) by (node)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{node=~\"$node\", name!=\"\"}) by (node)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Pod Resource Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{node=~\"$node\", name!=\"\", pod!=\"\"}[5m])) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10, sum(container_memory_working_set_bytes{node=~\"$node\", name!=\"\", pod!=\"\"}) by (pod))",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}