{{- $args := dict
  "checksumAnnotations" (dict
    "envCM"     "configmap.yaml"
    "envSecret" "secret.yaml"
  )
  "container" (dict
    "image" (empty .Values.image.tag | ternary (merge .Values.image (dict "tag" .Chart.AppVersion)) .Values.image)
    "ports" (dict
      "http" 3000
    )
    "envVars" (dict
      "MB_JETTY_HOST" "0.0.0.0"
      "MB_JETTY_PORT" 3000
    )
    "envVarsCM" (include "common.names.fullname" .)
    "envVarsSecret" (include "common.names.fullname" .)
    "livenessProbe" (dict
      "httpGet" (dict
        "path" "/api/health"
        "port" 3000
      )
    )
    "readinessProbe" (dict
      "httpGet" (dict
        "path" "/"
        "port" 3000
      )
    )
    "volumeMounts" (eq .Values.database.type "h2" | ternary
      (list
        (dict
          "name"      "data"
          "mountPath" "/metabase.db"
        )
      )
      nil
    )
  )
  "volumes" (eq .Values.database.type "h2" | ternary
    (list
      (dict
        (.Values.persistence.enabled | ternary
          (empty .Values.persistence.hostPath | ternary
            (dict
              "name" "data"
              "persistentVolumeClaim" (dict
                "claimName" (include "common.names.fullname" .)
              )
            )
            (dict
              "name" "data"
              "hostPath" (dict
                "path" .Values.persistence.hostPath
              )
            )
          )
          (dict
            "name" "data"
            "emptyDir" dict
          )
        )
      )
    )
    nil
  )
-}}

{{- include "tplchart.deployment" (dict
  "args" $args
  "values" (dict
    "deployment" .Values
  )
  "context" .
) -}}
