{{- define "morpheus.envSecrets" -}}
{{ if .Values.encryptionKey -}}
MB_ENCRYPTION_SECRET_KEY: {{ .Values.encryptionKey | b64enc | quote }}
{{ end -}}
{{ if not (eq .Values.database.type "h2") -}}
MB_DB_USER: {{ .Values.database.username | b64enc | quote }}
MB_DB_PASS: {{ .Values.database.password | b64enc | quote }}
{{ end -}}
MB_EMAIL_SMTP_USERNAME: {{ .Values.mail.smtp.username | b64enc | quote }}
MB_EMAIL_SMTP_PASSWORD: {{ .Values.mail.smtp.password | b64enc | quote }}
{{- end -}}

{{- include "tplchart.secret" (dict
  "args" (dict
    "data" (include "morpheus.envSecrets" .)
  )
  "values" .Values
  "context" .
) -}}
