apiVersion: v2
name: db-init
description: Init script to create multiple databases and users for MySQL/MariaDB and PostgreSQL
type: application
version: 1.2.0
dependencies:
- name: common
  version: 2.23.0
  repository: oci://registry-1.docker.io/bitnamicharts
