{{- define "nginx-s3-gateway.envSecret" -}}
AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKey | quote }}
AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretKey | quote }}
{{- end -}}

{{- include "tplchart.secret" (dict
  "Args" (dict
    "stringData" (include "nginx-s3-gateway.envSecret" .)
  )
  "context" .
) -}}
