{{- if not .Values.postgresql.existingSecret -}}
{{- include "tplchart.secret" (dict
  "Args" (dict
    "stringData" (dict
      "DATABASE_URL" (include "pgweb.databaseUrl" .)
    )
  )
  "context" .
) -}}
{{- end -}}
